# steps:
# - name:'gcr.io/cloud-builders/docker'
# args:
#  - build
#  - '-t'
#  - 'asia-south1-docker.pkg.dev/project-125a5906-9774-4549-bad/imageregistry/nginx:$SHORT_SHA'
#  - '.'
# - name:'gcr.io/cloud-builders/docker'
# args:
#  - push
#  - 'asia-south1-docker.pkg.dev/project-125a5906-9774-4549-bad/imageregistry/nginx:$SHORT_SHA'
# images:
# - 'asia-south1-docker.pkg.dev/project-125a5906-9774-4549-bad/imageregistry/nginx:$SHORT_SHA'

steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - asia-south1-docker.pkg.dev/project-125a5906-9774-4549-bad/imageregistry/nginx:$SHORT_SHA
      - .
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - asia-south1-docker.pkg.dev/project-125a5906-9774-4549-bad/imageregistry/nginx:$SHORT_SHA

  - name: ubuntu
    entrypoint: bash
    args:
    - '-c'
    - | 
        sed -i "s|IMAGE_URL|asia-south1-docker.pkg.dev/project-125a5906-9774-4549-bad/imageregistry/nginx:$SHORT_SHA|g" deployment.yml
        cat deployment.yml

  - name: gcr.io/cloud-builders/gcloud
    args:
      - container
      - clusters
      - get-credentials
      - demo-cluster
      - --region
      - us-central1
      - --project
      - project-125a5906-9774-4549-bad


options:
  logging: CLOUD_LOGGING_ONLY
images:
  - asia-south1-docker.pkg.dev/project-125a5906-9774-4549-bad/imageregistry/nginx:$SHORT_SHA

  
